# JK BMS configuration
#
# When using polling mode, each BMS must have a name which can be anything except "jk_sniffer"
# You must set the correct modbus ID and serial port to use to communicate with each individual BMS.
#
# When using sniffing mode, simply uncomming the "jk_sniffer" section and set the right port to use.
bms:
  # Polling mode
  # jk0:
  #   id: 0
  #   port: "/dev/ttyACM0"
  #
  # jk1:
  #   id: 1
  #   port: "/dev/ttyACM1"
  #
  # jk2:
  #   id: 2
  #   port: "/dev/ttyACM2"
  #
  # jk3:
  #   id: 3
  #   port: "/dev/ttyACM3"
  #
  # Sniffing mode
  jk_sniffer:
    port: "/dev/ttyUSB0"

# Conext InsightHome configuration.
# ids is optional, but will make things faster and allows you to skip modbus devices
insighthome:
  host: "192.168.1.5"
  port: 503
  ids: [10,50,170,171,190]

# If you want to push data in MQTT (for the GUI part of BerryBMS, Node-RED, etc.)
# you must set the host/port where to push it. You can use the default
# settings with a locally installed mosquitto MQTT server.
mqtt:
  host: "localhost"
  port: 1883

# If you run BerryBMS as a daemon (command line or through systemd)
# you can set your preferred update interval in seconds.
updateinterval: 300
